name: Season-9-5
version: '${project.version}'
main: com.bernardo.Season95
api-version: '1.20'
commands:
  regras:
    description: Regras do server
    usage: /regras
  twitch:
    description: Twitch do Excambaw
    usage: /twitch
    aliases:
      - live
      - twitch
  youtube:
    description: Youtube do Excambaw
    usage: /youtube
    aliases:
      - yt
  host:
    description: Astral Host
    usage: /host
    aliases:
      - astral