name: Season-9-5
version: '${project.version}'
main: com.bernardo.Season95
api-version: '1.20'
commands:
  regras:
    description: Regras
    usage: /regras
  twitch:
    description: Twitch do Excambaw
    usage: /twitch
    aliases:
      - live
      - twitch
  youtube:
    description: Youtube do Excambaw
    usage: /youtube
    aliases:
      - yt
  host:
    description: Astral Host
    usage: /host
    aliases:
      - astral
  loja:
    description: Loja de Vips, Unbans e Cosméticos
    usage: /loja
    aliases:
      - cosmeticos
  liveon:
    description: Aviso de Live On
    usage: /liveon
    permission:
      season-9-5.liveon
    aliases:
      - l
  tutorialterreno:
    description: Tutorial de Proteção de Terreno
    usage: /tutorialterreno
    aliases:
      - terreno
  tutorialvip:
    description: Tutorial dos Vips
    usage: /tutorialvips
    aliases:
      - vips
      - vip
      - tags
  tutorialloja:
    description: Tutorial de Economia
    usage: /tutorialloja
  vipgratis:
    description: Comando de Vip Grátis
    usage: /vipgratis
  encantamentos:
    description: Encantamentos Customizados
    usage: /encantamentos