name: Season-9-5
version: '1.0-SNAPSHOT'
main: com.bernardo.Season95
api-version: '1.20'
commands:
  regras:
    description: Regras do server
    usage: /regras
  twitch:
    description: Twitch do Excambaw
    usage: /twitch
    aliases:
      - live
      - twitch
  youtube:
    description: Youtube do Excambaw
    usage: /youtube
    aliases:
      - yt
  host:
    description: Astral Host
    usage: /host
    aliases:
      - astral
  loja:
    description: Loja de Vips, Unbans e Cosméticos de server
    usage: /loja
    aliases:
      - cosmeticos
  terreno:
    description: Tutorial de Proteção de Terreno
    usage: /terreno
    aliases:
      - tutorialterreno
      - tutorialclaim
  tags:
    description: Todas os Vips do Servidor
    usage: /tags
    aliases:
      - vip
      - vips
  liveon:
    description: Aviso de Live On
    usage: /liveon
    permission:
      season-9-5.liveon
    aliases:
      - l